[tool.poetry]
name = "netcam-aioeos"
version = "0.2.1"
description = "NetCAD - Arista EOS (asyncio) driver"
readme = "README.md"
authors = ["Jeremy Schulman"]

[tool.poetry.dependencies]
   python = ">=^3.8"

[tool.poetry.dev-dependencies]
    pytest = "*"
    invoke = "*"
    black = "*"
    flake8 = "*"
    flake8-breakpoint = "*"
    pytest-cov = "*"
    pytest-asyncio = "*"
    pre-commit = "*"
    interrogate = "*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.interrogate]
    fail-under = 0
    verbose = 1
    color = true
    ignore-module = true
    exclude = ["tasks.py", "examples", "build", "venv"]
